load("//Config:configs.bzl", "app_binary_configs", "library_configs", "watch_binary_configs", "message_binary_configs", "pretty", "info_plist_substitutions")
load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib", "apple_test_all")

apple_asset_catalog(
  name = "AppAsset",
  dirs = ["Assets.xcassets"],
  app_icon = "AppIcon",
)

apple_resource(
    name = "AppResources",
    dirs = [],
    files = glob(["*.png","*.xib","Base.lproj/*.storyboard"]),
)


apple_library(
    name = "AppLibrary",
    configs = library_configs(),
    swift_version = "4.2.1",
    srcs = [
        "ViewController.swift",
        "AppDelegate.swift",
    ],
    deps = [
        "//Pods:Alamofire",
        "//Pods:IGListKit",
        #"//Pods:FirebaseCore",
        #"//Pods:FirebaseAuth",
         "//Pods:Swinject",
         "//Pods:SwinjectStoryboard",
         "//Pods:RxSwift",
         "//Pods:RxCocoa",
#         "//Pods:KochavaTrackeriOS",
         "//Pods:ZDCChat",
         "//Pods:ZDCChatAPI",
         "//Pods:Fabric",
         "//Pods:Crashlytics",
         "//Pods:Mixpanel",
         "//Pods:SwiftyRSA",
         "//Pods:SwiftKeychainWrapper",
         "//Pods:SkyFloatingLabelTextField",
         "//Pods:CountryPickerSwift",
         "//Pods:Validator",
         "//Pods:SVProgressHUD",
         "//Pods:Intercom",
         "//Pods:Hero",
         "//Pods:Lottie",
         "//Pods:Armchair",
         "//Pods:IQKeyboardManagerSwift",
#         "//Pods:ZendeskCoreSDK",
#         "//Pods:ZendeskProviderSDK",
#         "//Pods:ZendeskSDK",
        #"//Pods:FBSDKCoreKit",
        #"//Pods:Protobuf",
        #"//Pods:FirebaseMessaging"
    ]
)
apple_binary(
    name = "AppBinary",
    configs = app_binary_configs("BuckTest"),
    swift_version = "4.2.1",
    deps = [":AppLibrary", ":AppAsset", ':AppResources'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
        '$SDKROOT/System/Library/Frameworks/AssetsLibrary.framework',
        '$SDKROOT/System/Library/Frameworks/CoreTelephony.framework',
    ],
)

apple_bundle(
    name = "BuckTest",
    binary = ":AppBinary",
    extension = "app",
    info_plist = "Info.plist",
    info_plist_substitutions = {
        "PRODUCT_BUNDLE_IDENTIFIER": "com.fundingsocieties.BuckTest",
        "CURRENT_PROJECT_VERSION": "1",
    },
)

apple_package(
  name = "PalmerahAppPackage",
  bundle = ":App",
)

apple_test(
    name = "AppTest",
    test_host_app = ":App",
    srcs = glob(["BuckTestTests/*.swift"]),
    info_plist = "BuckTestTests/Info.plist",
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
